/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/recycle_depot.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/recycle_depot.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.countertop_2.geometry} material={nodes.countertop_2.material} />
      <mesh geometry={nodes.garbage_can.geometry} material={nodes.garbage_can.material} />
      <mesh geometry={nodes.tap.geometry} material={nodes.tap.material} />
      <mesh geometry={nodes.sink_counter.geometry} material={nodes.sink_counter.material} />
      <mesh geometry={nodes.water.geometry} material={nodes.water.material} />
      <mesh geometry={nodes.counter_1.geometry} material={nodes.counter_1.material} />
      <mesh geometry={nodes.countertop_1.geometry} material={nodes.countertop_1.material} />
      <mesh geometry={nodes.conveyor_belt_base.geometry} material={nodes.conveyor_belt_base.material} />
      <mesh geometry={nodes.conveyor_belt.geometry} material={nodes.conveyor_belt.material} />
      <mesh geometry={nodes.counter_2.geometry} material={nodes.counter_2.material} />
      <mesh geometry={nodes.floor.geometry} material={nodes.floor.material} />
      <mesh geometry={nodes.walls.geometry} material={nodes.walls.material} />
      <mesh geometry={nodes.bin_1.geometry} material={nodes.bin_1.material} />
      <mesh geometry={nodes.bin_2.geometry} material={nodes.bin_2.material} />
      <mesh geometry={nodes.bin_3.geometry} material={nodes.bin_3.material} />
    </group>
  )
}

useGLTF.preload('/recycle_depot.gltf')
